name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Run static checks
        run: npm allstatic

      # Tests require to run on replit, we'll add it to PRs
      # via custom github webhooks
      # - name: Run Tests
      #   run: npm run test
